// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: record.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from record.proto</summary>
public static partial class RecordReflection {

  #region Descriptor
  /// <summary>File descriptor for record.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RecordReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxyZWNvcmQucHJvdG8iHwoGUmVjb3JkEhUKBlJlY29yZBgBIAMoCzIFLlN0",
          "ZXAiqAMKBFN0ZXASEgoKRnJhbWVDb3VudBgBIAEoBRISCgpHYW1lT2JqZWN0",
          "GAIgASgJEiAKBlN0YXR1cxgDIAEoDjIQLlN0ZXAuU3RhdHVzRW51bRIRCglQ",
          "b3NpdGlvblgYBCABKAISEQoJUG9zaXRpb25ZGAUgASgCEhEKCVBvc2l0aW9u",
          "WhgGIAEoAhIRCglSb3RhdGlvblgYByABKAISEQoJUm90YXRpb25ZGAggASgC",
          "EhEKCVJvdGF0aW9uWhgJIAEoAhIOCgZTY2FsZVgYCiABKAISDgoGU2NhbGVZ",
          "GAsgASgCEg4KBlNjYWxlWhgMIAEoAhIQCghSZXNvdXJjZRgNIAEoCRIKCgJJ",
          "RBgOIAEoCRIRCglIaWVyYXJjaHkYDyABKAkiggEKClN0YXR1c0VudW0SEAoM",
          "SW5zdGFudGlhdGVkEAASCwoHQ2hhbmdlZBABEg0KCURlc3Ryb3llZBACEg0K",
          "CUFjdGl2YXRlZBADEg8KC0RlYWN0aXZhdGVkEAQSEQoNSUZyYW1lX0FjdGl2",
          "ZRAFEhMKD0lGcmFtZV9JbmFjdGl2ZRAGIiUKCFVpUmVjb3JkEhkKCFVpUmVj",
          "b3JkGAEgAygLMgcuVWlTdGVwIp0BCgZVaVN0ZXASEgoKRnJhbWVDb3VudBgB",
          "IAEoBRIeCgRUeXBlGAIgASgOMhAuVWlTdGVwLlR5cGVFbnVtEhAKCE5ld1Zh",
          "bHVlGAMgASgJEhEKCUhpZXJhcmNoeRgEIAEoCRIKCgJJRBgFIAEoCSIuCghU",
          "eXBlRW51bRIKCgZCdXR0b24QABIKCgZUb2dnbGUQARIKCgZTbGlkZXIQAmIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Record), global::Record.Parser, new[]{ "Record_" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Step), global::Step.Parser, new[]{ "FrameCount", "GameObject", "Status", "PositionX", "PositionY", "PositionZ", "RotationX", "RotationY", "RotationZ", "ScaleX", "ScaleY", "ScaleZ", "Resource", "ID", "Hierarchy" }, null, new[]{ typeof(global::Step.Types.StatusEnum) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UiRecord), global::UiRecord.Parser, new[]{ "UiRecord_" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UiStep), global::UiStep.Parser, new[]{ "FrameCount", "Type", "NewValue", "Hierarchy", "ID" }, null, new[]{ typeof(global::UiStep.Types.TypeEnum) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Record : pb::IMessage<Record>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Record> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecordReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Record() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Record(Record other) : this() {
    record_ = other.record_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Record Clone() {
    return new Record(this);
  }

  /// <summary>Field number for the "Record" field.</summary>
  public const int Record_FieldNumber = 1;
  private static readonly pb::FieldCodec<global::Step> _repeated_record_codec
      = pb::FieldCodec.ForMessage(10, global::Step.Parser);
  private readonly pbc::RepeatedField<global::Step> record_ = new pbc::RepeatedField<global::Step>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Step> Record_ {
    get { return record_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Record);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Record other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!record_.Equals(other.record_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= record_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    record_.WriteTo(output, _repeated_record_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    record_.WriteTo(ref output, _repeated_record_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += record_.CalculateSize(_repeated_record_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Record other) {
    if (other == null) {
      return;
    }
    record_.Add(other.record_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          record_.AddEntriesFrom(input, _repeated_record_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          record_.AddEntriesFrom(ref input, _repeated_record_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Step : pb::IMessage<Step>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Step> _parser = new pb::MessageParser<Step>(() => new Step());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Step> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecordReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Step() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Step(Step other) : this() {
    frameCount_ = other.frameCount_;
    gameObject_ = other.gameObject_;
    status_ = other.status_;
    positionX_ = other.positionX_;
    positionY_ = other.positionY_;
    positionZ_ = other.positionZ_;
    rotationX_ = other.rotationX_;
    rotationY_ = other.rotationY_;
    rotationZ_ = other.rotationZ_;
    scaleX_ = other.scaleX_;
    scaleY_ = other.scaleY_;
    scaleZ_ = other.scaleZ_;
    resource_ = other.resource_;
    iD_ = other.iD_;
    hierarchy_ = other.hierarchy_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Step Clone() {
    return new Step(this);
  }

  /// <summary>Field number for the "FrameCount" field.</summary>
  public const int FrameCountFieldNumber = 1;
  private int frameCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int FrameCount {
    get { return frameCount_; }
    set {
      frameCount_ = value;
    }
  }

  /// <summary>Field number for the "GameObject" field.</summary>
  public const int GameObjectFieldNumber = 2;
  private string gameObject_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameObject {
    get { return gameObject_; }
    set {
      gameObject_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Status" field.</summary>
  public const int StatusFieldNumber = 3;
  private global::Step.Types.StatusEnum status_ = global::Step.Types.StatusEnum.Instantiated;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Step.Types.StatusEnum Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "PositionX" field.</summary>
  public const int PositionXFieldNumber = 4;
  private float positionX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionX {
    get { return positionX_; }
    set {
      positionX_ = value;
    }
  }

  /// <summary>Field number for the "PositionY" field.</summary>
  public const int PositionYFieldNumber = 5;
  private float positionY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionY {
    get { return positionY_; }
    set {
      positionY_ = value;
    }
  }

  /// <summary>Field number for the "PositionZ" field.</summary>
  public const int PositionZFieldNumber = 6;
  private float positionZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionZ {
    get { return positionZ_; }
    set {
      positionZ_ = value;
    }
  }

  /// <summary>Field number for the "RotationX" field.</summary>
  public const int RotationXFieldNumber = 7;
  private float rotationX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float RotationX {
    get { return rotationX_; }
    set {
      rotationX_ = value;
    }
  }

  /// <summary>Field number for the "RotationY" field.</summary>
  public const int RotationYFieldNumber = 8;
  private float rotationY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float RotationY {
    get { return rotationY_; }
    set {
      rotationY_ = value;
    }
  }

  /// <summary>Field number for the "RotationZ" field.</summary>
  public const int RotationZFieldNumber = 9;
  private float rotationZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float RotationZ {
    get { return rotationZ_; }
    set {
      rotationZ_ = value;
    }
  }

  /// <summary>Field number for the "ScaleX" field.</summary>
  public const int ScaleXFieldNumber = 10;
  private float scaleX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScaleX {
    get { return scaleX_; }
    set {
      scaleX_ = value;
    }
  }

  /// <summary>Field number for the "ScaleY" field.</summary>
  public const int ScaleYFieldNumber = 11;
  private float scaleY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScaleY {
    get { return scaleY_; }
    set {
      scaleY_ = value;
    }
  }

  /// <summary>Field number for the "ScaleZ" field.</summary>
  public const int ScaleZFieldNumber = 12;
  private float scaleZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScaleZ {
    get { return scaleZ_; }
    set {
      scaleZ_ = value;
    }
  }

  /// <summary>Field number for the "Resource" field.</summary>
  public const int ResourceFieldNumber = 13;
  private string resource_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Resource {
    get { return resource_; }
    set {
      resource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ID" field.</summary>
  public const int IDFieldNumber = 14;
  private string iD_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ID {
    get { return iD_; }
    set {
      iD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Hierarchy" field.</summary>
  public const int HierarchyFieldNumber = 15;
  private string hierarchy_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Hierarchy {
    get { return hierarchy_; }
    set {
      hierarchy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Step);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Step other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FrameCount != other.FrameCount) return false;
    if (GameObject != other.GameObject) return false;
    if (Status != other.Status) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionX, other.PositionX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionY, other.PositionY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionZ, other.PositionZ)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotationX, other.RotationX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotationY, other.RotationY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotationZ, other.RotationZ)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScaleX, other.ScaleX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScaleY, other.ScaleY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScaleZ, other.ScaleZ)) return false;
    if (Resource != other.Resource) return false;
    if (ID != other.ID) return false;
    if (Hierarchy != other.Hierarchy) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (FrameCount != 0) hash ^= FrameCount.GetHashCode();
    if (GameObject.Length != 0) hash ^= GameObject.GetHashCode();
    if (Status != global::Step.Types.StatusEnum.Instantiated) hash ^= Status.GetHashCode();
    if (PositionX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionX);
    if (PositionY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionY);
    if (PositionZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionZ);
    if (RotationX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotationX);
    if (RotationY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotationY);
    if (RotationZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotationZ);
    if (ScaleX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScaleX);
    if (ScaleY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScaleY);
    if (ScaleZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScaleZ);
    if (Resource.Length != 0) hash ^= Resource.GetHashCode();
    if (ID.Length != 0) hash ^= ID.GetHashCode();
    if (Hierarchy.Length != 0) hash ^= Hierarchy.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (FrameCount != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(FrameCount);
    }
    if (GameObject.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GameObject);
    }
    if (Status != global::Step.Types.StatusEnum.Instantiated) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Status);
    }
    if (PositionX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(PositionX);
    }
    if (PositionY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(PositionY);
    }
    if (PositionZ != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(PositionZ);
    }
    if (RotationX != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(RotationX);
    }
    if (RotationY != 0F) {
      output.WriteRawTag(69);
      output.WriteFloat(RotationY);
    }
    if (RotationZ != 0F) {
      output.WriteRawTag(77);
      output.WriteFloat(RotationZ);
    }
    if (ScaleX != 0F) {
      output.WriteRawTag(85);
      output.WriteFloat(ScaleX);
    }
    if (ScaleY != 0F) {
      output.WriteRawTag(93);
      output.WriteFloat(ScaleY);
    }
    if (ScaleZ != 0F) {
      output.WriteRawTag(101);
      output.WriteFloat(ScaleZ);
    }
    if (Resource.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(Resource);
    }
    if (ID.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(ID);
    }
    if (Hierarchy.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(Hierarchy);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (FrameCount != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(FrameCount);
    }
    if (GameObject.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GameObject);
    }
    if (Status != global::Step.Types.StatusEnum.Instantiated) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Status);
    }
    if (PositionX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(PositionX);
    }
    if (PositionY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(PositionY);
    }
    if (PositionZ != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(PositionZ);
    }
    if (RotationX != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(RotationX);
    }
    if (RotationY != 0F) {
      output.WriteRawTag(69);
      output.WriteFloat(RotationY);
    }
    if (RotationZ != 0F) {
      output.WriteRawTag(77);
      output.WriteFloat(RotationZ);
    }
    if (ScaleX != 0F) {
      output.WriteRawTag(85);
      output.WriteFloat(ScaleX);
    }
    if (ScaleY != 0F) {
      output.WriteRawTag(93);
      output.WriteFloat(ScaleY);
    }
    if (ScaleZ != 0F) {
      output.WriteRawTag(101);
      output.WriteFloat(ScaleZ);
    }
    if (Resource.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(Resource);
    }
    if (ID.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(ID);
    }
    if (Hierarchy.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(Hierarchy);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (FrameCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameCount);
    }
    if (GameObject.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameObject);
    }
    if (Status != global::Step.Types.StatusEnum.Instantiated) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (PositionX != 0F) {
      size += 1 + 4;
    }
    if (PositionY != 0F) {
      size += 1 + 4;
    }
    if (PositionZ != 0F) {
      size += 1 + 4;
    }
    if (RotationX != 0F) {
      size += 1 + 4;
    }
    if (RotationY != 0F) {
      size += 1 + 4;
    }
    if (RotationZ != 0F) {
      size += 1 + 4;
    }
    if (ScaleX != 0F) {
      size += 1 + 4;
    }
    if (ScaleY != 0F) {
      size += 1 + 4;
    }
    if (ScaleZ != 0F) {
      size += 1 + 4;
    }
    if (Resource.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Resource);
    }
    if (ID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ID);
    }
    if (Hierarchy.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Hierarchy);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Step other) {
    if (other == null) {
      return;
    }
    if (other.FrameCount != 0) {
      FrameCount = other.FrameCount;
    }
    if (other.GameObject.Length != 0) {
      GameObject = other.GameObject;
    }
    if (other.Status != global::Step.Types.StatusEnum.Instantiated) {
      Status = other.Status;
    }
    if (other.PositionX != 0F) {
      PositionX = other.PositionX;
    }
    if (other.PositionY != 0F) {
      PositionY = other.PositionY;
    }
    if (other.PositionZ != 0F) {
      PositionZ = other.PositionZ;
    }
    if (other.RotationX != 0F) {
      RotationX = other.RotationX;
    }
    if (other.RotationY != 0F) {
      RotationY = other.RotationY;
    }
    if (other.RotationZ != 0F) {
      RotationZ = other.RotationZ;
    }
    if (other.ScaleX != 0F) {
      ScaleX = other.ScaleX;
    }
    if (other.ScaleY != 0F) {
      ScaleY = other.ScaleY;
    }
    if (other.ScaleZ != 0F) {
      ScaleZ = other.ScaleZ;
    }
    if (other.Resource.Length != 0) {
      Resource = other.Resource;
    }
    if (other.ID.Length != 0) {
      ID = other.ID;
    }
    if (other.Hierarchy.Length != 0) {
      Hierarchy = other.Hierarchy;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          FrameCount = input.ReadInt32();
          break;
        }
        case 18: {
          GameObject = input.ReadString();
          break;
        }
        case 24: {
          Status = (global::Step.Types.StatusEnum) input.ReadEnum();
          break;
        }
        case 37: {
          PositionX = input.ReadFloat();
          break;
        }
        case 45: {
          PositionY = input.ReadFloat();
          break;
        }
        case 53: {
          PositionZ = input.ReadFloat();
          break;
        }
        case 61: {
          RotationX = input.ReadFloat();
          break;
        }
        case 69: {
          RotationY = input.ReadFloat();
          break;
        }
        case 77: {
          RotationZ = input.ReadFloat();
          break;
        }
        case 85: {
          ScaleX = input.ReadFloat();
          break;
        }
        case 93: {
          ScaleY = input.ReadFloat();
          break;
        }
        case 101: {
          ScaleZ = input.ReadFloat();
          break;
        }
        case 106: {
          Resource = input.ReadString();
          break;
        }
        case 114: {
          ID = input.ReadString();
          break;
        }
        case 122: {
          Hierarchy = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          FrameCount = input.ReadInt32();
          break;
        }
        case 18: {
          GameObject = input.ReadString();
          break;
        }
        case 24: {
          Status = (global::Step.Types.StatusEnum) input.ReadEnum();
          break;
        }
        case 37: {
          PositionX = input.ReadFloat();
          break;
        }
        case 45: {
          PositionY = input.ReadFloat();
          break;
        }
        case 53: {
          PositionZ = input.ReadFloat();
          break;
        }
        case 61: {
          RotationX = input.ReadFloat();
          break;
        }
        case 69: {
          RotationY = input.ReadFloat();
          break;
        }
        case 77: {
          RotationZ = input.ReadFloat();
          break;
        }
        case 85: {
          ScaleX = input.ReadFloat();
          break;
        }
        case 93: {
          ScaleY = input.ReadFloat();
          break;
        }
        case 101: {
          ScaleZ = input.ReadFloat();
          break;
        }
        case 106: {
          Resource = input.ReadString();
          break;
        }
        case 114: {
          ID = input.ReadString();
          break;
        }
        case 122: {
          Hierarchy = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Step message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum StatusEnum {
      [pbr::OriginalName("Instantiated")] Instantiated = 0,
      [pbr::OriginalName("Changed")] Changed = 1,
      [pbr::OriginalName("Destroyed")] Destroyed = 2,
      [pbr::OriginalName("Activated")] Activated = 3,
      [pbr::OriginalName("Deactivated")] Deactivated = 4,
      [pbr::OriginalName("IFrame_Active")] IframeActive = 5,
      [pbr::OriginalName("IFrame_Inactive")] IframeInactive = 6,
    }

  }
  #endregion

}

public sealed partial class UiRecord : pb::IMessage<UiRecord>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UiRecord> _parser = new pb::MessageParser<UiRecord>(() => new UiRecord());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UiRecord> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecordReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiRecord() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiRecord(UiRecord other) : this() {
    uiRecord_ = other.uiRecord_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiRecord Clone() {
    return new UiRecord(this);
  }

  /// <summary>Field number for the "UiRecord" field.</summary>
  public const int UiRecord_FieldNumber = 1;
  private static readonly pb::FieldCodec<global::UiStep> _repeated_uiRecord_codec
      = pb::FieldCodec.ForMessage(10, global::UiStep.Parser);
  private readonly pbc::RepeatedField<global::UiStep> uiRecord_ = new pbc::RepeatedField<global::UiStep>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::UiStep> UiRecord_ {
    get { return uiRecord_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UiRecord);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UiRecord other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!uiRecord_.Equals(other.uiRecord_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= uiRecord_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    uiRecord_.WriteTo(output, _repeated_uiRecord_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    uiRecord_.WriteTo(ref output, _repeated_uiRecord_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += uiRecord_.CalculateSize(_repeated_uiRecord_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UiRecord other) {
    if (other == null) {
      return;
    }
    uiRecord_.Add(other.uiRecord_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          uiRecord_.AddEntriesFrom(input, _repeated_uiRecord_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          uiRecord_.AddEntriesFrom(ref input, _repeated_uiRecord_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class UiStep : pb::IMessage<UiStep>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UiStep> _parser = new pb::MessageParser<UiStep>(() => new UiStep());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UiStep> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RecordReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiStep() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiStep(UiStep other) : this() {
    frameCount_ = other.frameCount_;
    type_ = other.type_;
    newValue_ = other.newValue_;
    hierarchy_ = other.hierarchy_;
    iD_ = other.iD_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UiStep Clone() {
    return new UiStep(this);
  }

  /// <summary>Field number for the "FrameCount" field.</summary>
  public const int FrameCountFieldNumber = 1;
  private int frameCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int FrameCount {
    get { return frameCount_; }
    set {
      frameCount_ = value;
    }
  }

  /// <summary>Field number for the "Type" field.</summary>
  public const int TypeFieldNumber = 2;
  private global::UiStep.Types.TypeEnum type_ = global::UiStep.Types.TypeEnum.Button;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UiStep.Types.TypeEnum Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "NewValue" field.</summary>
  public const int NewValueFieldNumber = 3;
  private string newValue_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NewValue {
    get { return newValue_; }
    set {
      newValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Hierarchy" field.</summary>
  public const int HierarchyFieldNumber = 4;
  private string hierarchy_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Hierarchy {
    get { return hierarchy_; }
    set {
      hierarchy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ID" field.</summary>
  public const int IDFieldNumber = 5;
  private string iD_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ID {
    get { return iD_; }
    set {
      iD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UiStep);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UiStep other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FrameCount != other.FrameCount) return false;
    if (Type != other.Type) return false;
    if (NewValue != other.NewValue) return false;
    if (Hierarchy != other.Hierarchy) return false;
    if (ID != other.ID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (FrameCount != 0) hash ^= FrameCount.GetHashCode();
    if (Type != global::UiStep.Types.TypeEnum.Button) hash ^= Type.GetHashCode();
    if (NewValue.Length != 0) hash ^= NewValue.GetHashCode();
    if (Hierarchy.Length != 0) hash ^= Hierarchy.GetHashCode();
    if (ID.Length != 0) hash ^= ID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (FrameCount != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(FrameCount);
    }
    if (Type != global::UiStep.Types.TypeEnum.Button) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Type);
    }
    if (NewValue.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(NewValue);
    }
    if (Hierarchy.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Hierarchy);
    }
    if (ID.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (FrameCount != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(FrameCount);
    }
    if (Type != global::UiStep.Types.TypeEnum.Button) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Type);
    }
    if (NewValue.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(NewValue);
    }
    if (Hierarchy.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Hierarchy);
    }
    if (ID.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (FrameCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameCount);
    }
    if (Type != global::UiStep.Types.TypeEnum.Button) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (NewValue.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NewValue);
    }
    if (Hierarchy.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Hierarchy);
    }
    if (ID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UiStep other) {
    if (other == null) {
      return;
    }
    if (other.FrameCount != 0) {
      FrameCount = other.FrameCount;
    }
    if (other.Type != global::UiStep.Types.TypeEnum.Button) {
      Type = other.Type;
    }
    if (other.NewValue.Length != 0) {
      NewValue = other.NewValue;
    }
    if (other.Hierarchy.Length != 0) {
      Hierarchy = other.Hierarchy;
    }
    if (other.ID.Length != 0) {
      ID = other.ID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          FrameCount = input.ReadInt32();
          break;
        }
        case 16: {
          Type = (global::UiStep.Types.TypeEnum) input.ReadEnum();
          break;
        }
        case 26: {
          NewValue = input.ReadString();
          break;
        }
        case 34: {
          Hierarchy = input.ReadString();
          break;
        }
        case 42: {
          ID = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          FrameCount = input.ReadInt32();
          break;
        }
        case 16: {
          Type = (global::UiStep.Types.TypeEnum) input.ReadEnum();
          break;
        }
        case 26: {
          NewValue = input.ReadString();
          break;
        }
        case 34: {
          Hierarchy = input.ReadString();
          break;
        }
        case 42: {
          ID = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the UiStep message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum TypeEnum {
      [pbr::OriginalName("Button")] Button = 0,
      [pbr::OriginalName("Toggle")] Toggle = 1,
      [pbr::OriginalName("Slider")] Slider = 2,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
